apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip
spec:
  
  selector:
    app: probe
  ports:
    - port: 8088 # port of svc to accept request
      targetPort: 80 # container port
      
